apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-diy-mutating-webhook
  name: k8s-diy-mutating-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: k8s-diy-mutating-webhook
